addons:
  postgresql: 9.6
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create extension postgis' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
dist: xenial #trusty
language: ruby
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - redis-server


