development:
  secret_key_base: ce4c380da77f36f967964c4272cda0e0b758ff2fca76829830b6e2173e700b0372ac80100095dd6ca58abbda90b192d6dbe32f50d6fe7ca7a8a74975bee6711e
  user_endpoint: <%= ENV.fetch('USER_ENDPOINT', 'http://localhost:3010/resources') %>
  user_token: <%= ENV.fetch('USER_TOKEN', 'DEFAULT_TOKEN') %>
  marketplace_endpoint: <%= ENV.fetch('MARKETPLACE_ENDPOINT', 'http://localhost:9090/services') %>
  marketplace_token: <%= ENV.fetch('MARKETPLACE_TOKEN', 'DEFAULT_TOKEN') %>
  allowed_origins: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3000') %> # In case you want multiple domains, just separe them with a comma (but do it in the .env file!)
  hostname: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost') %>
  redis_host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  redis_port: <%= ENV.fetch('REDIS_PORT', '6379') %>
  redis_db: <%= ENV.fetch('REDIS_DB', '2') %>
  rollbar_access_token: <%= ENV.fetch('ROLLBAR_ACCESS_TOKEN', '') %>
  aws_credentials_access_key: <%= ENV.fetch('AWS_CREDENTIALS_ACCESS_KEY', '') %>
  aws_credentials_secret_key: <%= ENV.fetch('AWS_CREDENTIALS_SECRET_KEY', '') %>
  aws_region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  aws_sns_arn_android: <%= ENV.fetch('AWS_SNS_ARN_ANDROID', '') %>
  mercadopago_payer_email_nilus: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_NILUS', 'test_user_92173722@testuser.com') %>
  mercadopago_payer_email_bar: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_BAR', 'test_user_92173722@testuser.com') %>
  mercadopago_payer_email_mdq: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_MDQ', 'test_user_62958989@testuser.com') %>
  mercadopago_mdq_public_key: <%= ENV.fetch('MERCADOPAGO_MDQ_PUBLIC_KEY', 'TEST-00699a26-4b22-4ccb-9d1f-c538a7e49550') %>
  mercadopago_mdq_access_token: <%= ENV.fetch('MERCADOPAGO_MDQ_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>
  mercadopago_bar_public_key: <%= ENV.fetch('MERCADOPAGO_BAR_PUBLIC_KEY', 'TEST-00699a26-4b22-4ccb-9d1f-c538a7e49550') %>
  mercadopago_bar_access_token: <%= ENV.fetch('MERCADOPAGO_BAR_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>
  mercadopago_nilus_public_key: <%= ENV.fetch('MERCADOPAGO_NILUS_PUBLIC_KEY', 'TEST-96b9b1c0-c7b6-4044-9241-a55876e90871') %>
  mercadopago_nilus_access_token: <%= ENV.fetch('MERCADOPAGO_NILUS_ACCESS_TOKEN', 'TEST-75555609726150-042314-4fca73ed8ef67b0758dcecba4f61f3d8-316516415') %>

test:
  secret_key_base: 25195f1d108b33e588ab69b9f2c2f848f676a453f39b0b99671845fb25dfd3cd8feeaa10bba5f59d6dbf636ade7657fc356ff9cdabff19ca7ec694311abbc341
  user_endpoint: <%= ENV.fetch('USER_ENDPOINT', 'http://localhost:3010/resources') %>
  user_token: <%= ENV.fetch('USER_TOKEN', 'DEFAULT_TOKEN') %>
  marketplace_endpoint: <%= ENV.fetch('MARKETPLACE_ENDPOINT', 'http://localhost:9090/services') %>
  marketplace_token: <%= ENV.fetch('MARKETPLACE_TOKEN', 'DEFAULT_TOKEN') %>
  allowed_origins: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3000') %> # In case you want multiple domains, just separe them with a comma (but do it in the .env file!)
  hostname: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost') %>
  redis_host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  redis_port: <%= ENV.fetch('REDIS_PORT', '6379') %>
  redis_db: <%= ENV.fetch('REDIS_DB', '2') %>
  rollbar_access_token: <%= ENV.fetch('ROLLBAR_ACCESS_TOKEN', '') %>
  aws_credentials_access_key: <%= ENV.fetch('AWS_CREDENTIALS_ACCESS_KEY', '') %>
  aws_credentials_secret_key: <%= ENV.fetch('AWS_CREDENTIALS_SECRET_KEY', 'R1pPJvDv3nmVaWDNYMM00VCWI9PanJgn08NoOS/A') %>
  aws_region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  aws_sns_arn_android: <%= ENV.fetch('AWS_SNS_ARN_ANDROID', '') %>
  mercadopago_payer_email_nilus: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_NILUS', 'test_user_92173722@testuser.com') %>
  mercadopago_payer_email_bar: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_BAR', 'test_user_92173722@testuser.com') %>
  mercadopago_payer_email_mdq: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_MDQ', 'test_user_62958989@testuser.com') %>
  mercadopago_mdq_public_key: <%= ENV.fetch('MERCADOPAGO_MDQ_PUBLIC_KEY', 'TEST-00699a26-4b22-4ccb-9d1f-c538a7e49550') %>
  mercadopago_mdq_access_token: <%= ENV.fetch('MERCADOPAGO_MDQ_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>
  mercadopago_bar_public_key: <%= ENV.fetch('MERCADOPAGO_BAR_PUBLIC_KEY', 'TEST-00699a26-4b22-4ccb-9d1f-c538a7e49550') %>
  mercadopago_bar_access_token: <%= ENV.fetch('MERCADOPAGO_BAR_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>
  mercadopago_nilus_public_key: <%= ENV.fetch('MERCADOPAGO_NILUS_PUBLIC_KEY', 'TEST-96b9b1c0-c7b6-4044-9241-a55876e90871') %>
  mercadopago_nilus_access_token: <%= ENV.fetch('MERCADOPAGO_NILUS_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user_endpoint: <%= ENV.fetch('USER_ENDPOINT', 'http://localhost:3010/services') %>
  user_token: <%= ENV.fetch('USER_TOKEN', 'DEFAULT_TOKEN') %>
  marketplace_endpoint: <%= ENV.fetch('MARKETPLACE_ENDPOINT', 'http://localhost:9090/services') %>
  marketplace_token: <%= ENV.fetch('MARKETPLACE_TOKEN', 'DEFAULT_TOKEN') %>
  allowed_origins: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3000') %> # In case you want multiple domains, just separe them with a comma (but do it in the .env file!)
  hostname: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3030') %>
  redis_host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  redis_port: <%= ENV.fetch('REDIS_PORT', '6379') %>
  redis_db: <%= ENV.fetch('REDIS_DB', '2') %>
  rollbar_access_token: <%= ENV.fetch('ROLLBAR_ACCESS_TOKEN', '') %>
  aws_credentials_access_key: <%= ENV.fetch('AWS_CREDENTIALS_ACCESS_KEY', '') %>
  aws_credentials_secret_key: <%= ENV.fetch('AWS_CREDENTIALS_SECRET_KEY', '') %>
  aws_region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  aws_sns_arn_android: <%= ENV.fetch('AWS_SNS_ARN_ANDROID', '') %>
  mercadopago_notification_host: <%= ENV.fetch('MERCADOPAGO_NOTIFICATION_HOST', '') %>
  mercadopago_payer_email_nilus: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_NILUS', 'test_user_92173722@testuser.com') %>
  mercadopago_payer_email_bar: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_BAR', 'test_user_92173722@testuser.com') %>
  mercadopago_payer_email_mdq: <%= ENV.fetch('MERCADOPAGO_PAYER_EMAIL_MDQ', 'test_user_62958989@testuser.com') %>
  mercadopago_mdq_public_key: <%= ENV.fetch('MERCADOPAGO_MDQ_PUBLIC_KEY', 'TEST-00699a26-4b22-4ccb-9d1f-c538a7e49550') %>
  mercadopago_mdq_access_token: <%= ENV.fetch('MERCADOPAGO_MDQ_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>
  mercadopago_bar_public_key: <%= ENV.fetch('MERCADOPAGO_BAR_PUBLIC_KEY', 'TEST-00699a26-4b22-4ccb-9d1f-c538a7e49550') %>
  mercadopago_bar_access_token: <%= ENV.fetch('MERCADOPAGO_BAR_ACCESS_TOKEN', 'TEST-463061222647738-042314-37ded60b57e20507d4ca94d4aa3124f3-316519508') %>
  mercadopago_nilus_public_key: <%= ENV.fetch('MERCADOPAGO_NILUS_PUBLIC_KEY', 'TEST-96b9b1c0-c7b6-4044-9241-a55876e90871') %>
  mercadopago_nilus_access_token: <%= ENV.fetch('MERCADOPAGO_NILUS_ACCESS_TOKEN', 'TEST-75555609726150-042314-4fca73ed8ef67b0758dcecba4f61f3d8-316516415') %>
